#!/bin/bash

mysql -u root -e \
"CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE; \
CREATE USER IF NOT EXISTS '$MYSQL_USER'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD'; \
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'localhost'; \
FLUSH PRIVILEGES;"

